### ISSUE TITLE
Discuss more questions

### ISSUE THREAD

**Issue by littleggghost** [MAVProxyUser/CyberquadForKidsTeardown#1]
Hi @MAVProxyUser 
Could I have your eamil？I want to discuss some questions with you.
Thanks in advance.
BR

**Comment by MAVProxyUser** [comment]
give me yours... I'll email you.

**Comment by littleggghost** [comment]
2386824377@qq.com
Thanks

**Comment by MAVProxyUser** [comment]
emailed.
